[package]
name = "texas_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
log = "0.4.29"
poker_lib = { path = "../../poker/lib" }
