[package]
name = "colorblk_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_pixel = { path = "../../../rust-pixel", default-features = false, features = ["base"] }
colorblk_lib = { path = "../lib" }

[lib]
crate-type=["staticlib","cdylib"]
