# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    permissions:
      contents: write  # 为 GITHUB_TOKEN 设置内容写权限

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Install deps
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          brew install ffmpeg            
          brew install sdl2
          brew install sdl2_image
          brew install sdl2_gfx
          brew install sdl2_ttf
          brew install sdl2_mixer

      # Runs a single command using the runners shell
      - name: Install cargo-pixel
        run: cargo install --path tools/cargo-pixel --root ~/.cargo

      - name: Build petview wasm
        run: |
          cargo pixel b petview w -r
          ls -la ./tmp/web_petview
          cp -r ./tmp/web_petview ./web_petview
          ls -la ./web_petview/pkg/

      # Runs a set of commands using the runners shell
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web_petview 
          publish_branch: gh-pages
